apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.wp.name }}
  labels:
{{- toYaml .Values.wp.labels | nindent 4 }}
  annotations:
{{- if .Values.wp.metrics.enabled }}
    prometheus.io/scrape: "true"
    prometheus.io/port: "9117"
    prometheus.io/path: "/metrics"
{{- end }}
spec:
  selector:
{{- toYaml .Values.wp.labels | nindent 4 }}
  ports:
  - name: web
    port: {{ .Values.wp.service.port }}
    targetPort: {{ .Values.wp.service.targetPort }}
    protocol: TCP
{{- if .Values.wp.metrics.enabled }}
  - name: metrics
    port: 9117
    targetPort: 9117
    protocol: TCP
{{- end }}
  type: {{ .Values.wp.service.type }}
