wp:
  name: wp-app
  labels:
    id: C0927678
    app: wordpress
    env: dev
  image:
    repository: wordpress
    tag: latest
    pullPolicy: Always
  replicas: 3
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1
  resources:
    requests:
      cpu: "150m"
      memory: "128Mi"
    limits:
      cpu: "250m"
      memory: "256Mi"
  configmap:
    WORDPRESS_DB_HOST: "wp-database.wpdb.svc.cluster.local:3306"
    WORDPRESS_DB_USER: wordpress
    WORDPRESS_DB_NAME: wordpress
    APP_ENV: dev
  service:
    type: ClusterIP
    port: 80
    targetPort: 80
  metrics:
    enabled: true

  # Add metrics configuration for Prometheus
  prometheus:
    enabled: true
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9117"
    serviceMonitor:
      enabled: true
      interval: 30s
      metricRelabelings:
        - sourceLabels: [__param_target]
          targetLabel: target
        - targetLabel: __address__
          replacement: wordpress-exporter:9117  # Replace with your exporter service name
